name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-latest] # arm64-darwin, x86_64-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build
        run: nix build --accept-flake-config
      - name: stage artifact
        run: |
          mkdir -p dist
          cp result/bin/sinete "dist/sinete-${{ runner.os }}-${{ runner.arch }}"
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: true
          generate_release_notes: true
